spring:
  application:
    name: gym-crm-system
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

hibernate:
  show_sql: false
  format_sql: false
  current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    io.github.mrergos.gymcrm: INFO