db.driver=org.h2.Driver
db.url=jdbc:h2:file:./data/gymcrm;AUTO_SERVER=TRUE
db.username=sa
db.password=

db.pool.maximumPoolSize=10
db.pool.minimumIdle=2

hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.dialect=org.hibernate.dialect.H2Dialect
hibernate.current_session_context_class=org.springframework.orm.hibernate6.SpringSessionContext